# Generated by Django 4.2.29 on 2026-04-01 11:06

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Основное фото товара (обязательно для отображения)', null=True, upload_to=store.models.product_image_upload_path, verbose_name='Главное фото'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Дополнительное фото товара', null=True, upload_to=store.models.product_image_upload_path, verbose_name='Дополнительное фото 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.product_image_upload_path, verbose_name='Дополнительное фото 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.product_image_upload_path, verbose_name='Дополнительное фото 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.product_image_upload_path, verbose_name='Дополнительное фото 5'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +7XXXXXXXXXX, 8XXXXXXXXXX или 7XXXXXXXXXX', max_length=20, validators=[store.models.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
