# Generated by Django 4.2.29 on 2026-04-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_collection_collectionproduct_collection_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instruction_file',
            field=models.FileField(blank=True, help_text='Загрузите PDF инструкцию (опционально)', null=True, upload_to='instructions/', verbose_name='Инструкция к товару'),
        ),
    ]
