# Generated by Django 4.2.29 on 2026-04-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_instruction_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_link',
            field=models.URLField(blank=True, help_text='Ссылка на видеообзор, сайт производителя или дополнительную информацию', null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='instruction_file',
            field=models.FileField(blank=True, help_text='Загрузите инструкцию', null=True, upload_to='instructions/', verbose_name='Инструкция к товару'),
        ),
    ]
